let
    Источник = Web.Contents("https://astanahub.com/en/service/techpark/"),
    #"Извлеченная таблица из HTML" = Html.Table(Источник, {{"Column1", "TABLE.table > * > TR > :nth-child(1)"}, {"Column2", "TABLE.table > * > TR > :nth-child(2)"}, {"Column3", "TABLE.table > * > TR > :nth-child(3)"}, {"Column4", "TABLE.table > * > TR > :nth-child(4)"}, {"Column5", "TABLE.table > * > TR > :nth-child(5)"}, {"Column6", "TABLE.table > * > TR > :nth-child(6)"}}, [RowSelector="TABLE.table > * > TR"]),
    #"Повышенные заголовки" = Table.PromoteHeaders(#"Извлеченная таблица из HTML", [PromoteAllScalars=true]),
    #"Добавлен пользовательский объект" = Table.AddColumn(#"Повышенные заголовки", "Year of registration", each Text.Middle([BIN],0,2)),
    #"Измененный тип" = Table.TransformColumnTypes(#"Добавлен пользовательский объект",{{"Year of registration", type text}}),
    #"Добавлен пользовательский объект1" = Table.AddColumn(#"Измененный тип", "Month of registration", each Text.Middle([BIN],2,2)),
    #"Измененный тип1" = Table.TransformColumnTypes(#"Добавлен пользовательский объект1",{{"Month of registration", type text}}),
    #"Добавлен пользовательский объект2" = Table.AddColumn(#"Измененный тип1", "form of entrepreneurship and residence", each Text.Middle([BIN],4,1)),
    #"Измененный тип2" = Table.TransformColumnTypes(#"Добавлен пользовательский объект2",{{"form of entrepreneurship and residence", type text}}),
    #"Добавлен пользовательский объект3" = Table.AddColumn(#"Измененный тип2", "Organizational and legal form", each Text.Middle([BIN],5,1)),
    #"Добавлен пользовательский объект4" = Table.AddColumn(#"Добавлен пользовательский объект3", "Registration number", each Text.Middle([BIN],6,5)),
    #"Измененный тип3" = Table.TransformColumnTypes(#"Добавлен пользовательский объект4",{{"Organizational and legal form", type text}, {"Registration number", type text}}),
    #"Добавлен пользовательский объект5" = Table.AddColumn(#"Измененный тип3", "Valid BIN (12)", each Text.Length([BIN])),
    #"Измененный тип4" = Table.TransformColumnTypes(#"Добавлен пользовательский объект5",{{"Valid BIN (12)", type text}}),
    #"Условный столбец добавлен" = Table.AddColumn(#"Измененный тип4", "BIN11", each if [#"Valid BIN (12)"] = "11" then [BIN] else null),
    #"Измененный тип5" = Table.TransformColumnTypes(#"Условный столбец добавлен",{{"BIN11", type text}}),
    #"Добавлен пользовательский объект6" = Table.AddColumn(#"Измененный тип5", "0", each 0),
    #"Измененный тип6" = Table.TransformColumnTypes(#"Добавлен пользовательский объект6",{{"0", type text}}),
    #"Объединенные столбцы" = Table.CombineColumns(#"Измененный тип6",{"0", "BIN11"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"Сведено"),
    #"Добавлен пользовательский объект7" = Table.AddColumn(#"Объединенные столбцы", "Пользовательский", each Text.Length([Сведено])),
    #"Переименованные столбцы" = Table.RenameColumns(#"Добавлен пользовательский объект7",{{"Сведено", "BIN11&0"}, {"Пользовательский", "Valid BIN 11&0"}}),
    #"Условный столбец добавлен1" = Table.AddColumn(#"Переименованные столбцы", "Пользовательский", each if [#"Valid BIN (12)"] = "12" then [BIN] else if [#"Valid BIN 11&0"] = 12 then [#"BIN11&0"] else null),
    #"Измененный тип7" = Table.TransformColumnTypes(#"Условный столбец добавлен1",{{"Valid BIN 11&0", type text}, {"Пользовательский", type text}}),
    #"Удаленные столбцы" = Table.RemoveColumns(#"Измененный тип7",{"Registration number", "Organizational and legal form", "Year of registration", "Month of registration", "form of entrepreneurship and residence"}),
    #"Переименованные столбцы1" = Table.RenameColumns(#"Удаленные столбцы",{{"Пользовательский", "BIN FINAL"}}),
    #"Добавлен пользовательский объект8" = Table.AddColumn(#"Переименованные столбцы1", "YEAR OF REGISTRATION", each Text.Middle([BIN FINAL],0,2)),
    #"Измененный тип8" = Table.TransformColumnTypes(#"Добавлен пользовательский объект8",{{"YEAR OF REGISTRATION", type text}}),
    #"Добавлен пользовательский объект9" = Table.AddColumn(#"Измененный тип8", "MONTH OF REGISTRATION", each Text.Middle([BIN FINAL],2,2)),
    #"Измененный тип9" = Table.TransformColumnTypes(#"Добавлен пользовательский объект9",{{"MONTH OF REGISTRATION", type text}}),
    #"Разделить столбец по положению" = Table.SplitColumn(#"Измененный тип9", "YEAR OF REGISTRATION", Splitter.SplitTextByRepeatedLengths(1), {"YEAR OF REGISTRATION.1", "YEAR OF REGISTRATION.2"}),
    #"Измененный тип10" = Table.TransformColumnTypes(#"Разделить столбец по положению",{{"YEAR OF REGISTRATION.1", type text}, {"YEAR OF REGISTRATION.2", type text}}),
    #"Условный столбец добавлен2" = Table.AddColumn(#"Измененный тип10", "YOR", each if [YEAR OF REGISTRATION.1] = "0" then 20 else if [YEAR OF REGISTRATION.1] = "1" then 20 else if [YEAR OF REGISTRATION.1] = "2" then 20 else if [YEAR OF REGISTRATION.1] = "3" then 20 else 19),
    #"Измененный тип11" = Table.TransformColumnTypes(#"Условный столбец добавлен2",{{"YOR", type text}}),
    #"Объединенные столбцы1" = Table.CombineColumns(#"Измененный тип11",{"YOR", "YEAR OF REGISTRATION.1", "YEAR OF REGISTRATION.2"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"YEAR oF REGISTRATIONN"),
    #"Переименованные столбцы2" = Table.RenameColumns(#"Объединенные столбцы1",{{"YEAR oF REGISTRATIONN", "YEAR OF REGISTRATION"}}),
    #"Объединенные столбцы2" = Table.CombineColumns(#"Переименованные столбцы2",{"MONTH OF REGISTRATION", "YEAR OF REGISTRATION"},Combiner.CombineTextByDelimiter(".", QuoteStyle.None),"DATE OF REGISTRATION"),
    #"Добавлен пользовательский объект10" = Table.AddColumn(#"Объединенные столбцы2", "YEAR OF REGISTRATION", each Text.Middle([DATE OF REGISTRATION],3,4)),
    #"Измененный тип12" = Table.TransformColumnTypes(#"Добавлен пользовательский объект10",{{"YEAR OF REGISTRATION", type text}}),
    #"Добавлен пользовательский объект11" = Table.AddColumn(#"Измененный тип12", "form of entrepreneurship and residence", each Text.Middle([BIN FINAL],4,1)),
    #"Измененный тип13" = Table.TransformColumnTypes(#"Добавлен пользовательский объект11",{{"form of entrepreneurship and residence", type text}}),
    #"Добавлен пользовательский объект12" = Table.AddColumn(#"Измененный тип13", "Organizational and legal form", each Text.Middle([BIN FINAL],5,1)),
    #"Добавлен пользовательский объект13" = Table.AddColumn(#"Добавлен пользовательский объект12", "Registration number", each Text.Middle([BIN FINAL],6,5)),
    #"Измененный тип14" = Table.TransformColumnTypes(#"Добавлен пользовательский объект13",{{"Organizational and legal form", type text}, {"Registration number", type text}}),
    #"Условный столбец добавлен3" = Table.AddColumn(#"Измененный тип14", "FORM OF ENTREPRENEURSHIP & RESIDENCE", each if [form of entrepreneurship and residence] = "4" then "Resident Legal Entity" else if [form of entrepreneurship and residence] = "5" then "Non-resident Legal Entity" else if [form of entrepreneurship and residence] = "6" then "Individual Entrepreneur" else null),
    #"Условный столбец добавлен4" = Table.AddColumn(#"Условный столбец добавлен3", "Пользовательский", each if [Organizational and legal form] = "0" then "Head Office" else if [Organizational and legal form] = "1" then "Branch" else if [Organizational and legal form] = "2" then "Representative Office" else if [Organizational and legal form] = "3" then "A Joint Peasant Farm" else null),
    #"Переименованные столбцы3" = Table.RenameColumns(#"Условный столбец добавлен4",{{"Пользовательский", "ORGANIZATIONAL & LEGAL FORM"}, {"COMPANY NAME", "COMPANY"}}),
    #"Измененный тип15" = Table.TransformColumnTypes(#"Переименованные столбцы3",{{"CERTIFICATE №", Int64.Type}}),
    #"Добавлен пользовательский объект14" = Table.AddColumn(#"Измененный тип15", "BIN_1", each Text.Middle([BIN FINAL],0,1)),
    #"Добавлен пользовательский объект15" = Table.AddColumn(#"Добавлен пользовательский объект14", "BIN_2", each Text.Middle([BIN FINAL],1,1)),
    #"Добавлен пользовательский объект16" = Table.AddColumn(#"Добавлен пользовательский объект15", "BIN_3", each Text.Middle([BIN FINAL],2,1)),
    #"Добавлен пользовательский объект17" = Table.AddColumn(#"Добавлен пользовательский объект16", "BIN_4", each Text.Middle([BIN FINAL],3,1)),
    #"Добавлен пользовательский объект18" = Table.AddColumn(#"Добавлен пользовательский объект17", "BIN_5", each Text.Middle([BIN FINAL],4,1)),
    #"Добавлен пользовательский объект19" = Table.AddColumn(#"Добавлен пользовательский объект18", "BIN_6", each Text.Middle([BIN FINAL],5,1)),
    #"Добавлен пользовательский объект20" = Table.AddColumn(#"Добавлен пользовательский объект19", "BIN_7", each Text.Middle([BIN FINAL],6,1)),
    #"Добавлен пользовательский объект21" = Table.AddColumn(#"Добавлен пользовательский объект20", "BIN_8", each Text.Middle([BIN FINAL],7,1)),
    #"Добавлен пользовательский объект22" = Table.AddColumn(#"Добавлен пользовательский объект21", "BIN_9", each Text.Middle([BIN FINAL],8,1)),
    #"Добавлен пользовательский объект23" = Table.AddColumn(#"Добавлен пользовательский объект22", "BIN_10", each Text.Middle([BIN FINAL],9,1)),
    #"Добавлен пользовательский объект24" = Table.AddColumn(#"Добавлен пользовательский объект23", "BIN_11", each Text.Middle([BIN FINAL],10,1)),
    #"Добавлен пользовательский объект25" = Table.AddColumn(#"Добавлен пользовательский объект24", "BIN_12", each Text.Middle([BIN FINAL],11,1)),
    #"Измененный тип16" = Table.TransformColumnTypes(#"Добавлен пользовательский объект25",{{"BIN_10", Int64.Type}, {"BIN_12", Int64.Type}, {"BIN_11", Int64.Type}, {"BIN_9", Int64.Type}, {"BIN_8", Int64.Type}, {"BIN_7", Int64.Type}, {"BIN_6", Int64.Type}, {"BIN_5", Int64.Type}, {"BIN_4", Int64.Type}, {"BIN_3", Int64.Type}, {"BIN_2", Int64.Type}, {"BIN_1", Int64.Type}}),
    #"Добавлен пользовательский объект26" = Table.AddColumn(#"Измененный тип16", "Пользовательский", each Number.Mod(([BIN_1]*1+[BIN_2]*2+[BIN_3]*3+[BIN_4]*4+[BIN_5]*5+[BIN_6]*6+[BIN_7]*7+[BIN_8]*8+[BIN_9]*9+[BIN_10]*10+[BIN_11]*11), 11)),
    #"Переименованные столбцы4" = Table.RenameColumns(#"Добавлен пользовательский объект26",{{"Пользовательский", "BIN_12(check_v1)"}}),
    #"Добавлен пользовательский объект27" = Table.AddColumn(#"Переименованные столбцы4", "BIN_12(check_v2)", each Number.Mod(([BIN_1]*3+[BIN_2]*4+[BIN_3]*5+[BIN_4]*6+[BIN_5]*7+[BIN_6]*8+[BIN_7]*9+[BIN_8]*10+[BIN_9]*11+[BIN_10]*1+[BIN_11]*2), 11)),
    #"Условный столбец добавлен5" = Table.AddColumn(#"Добавлен пользовательский объект27", "Пользовательский", each if [#"BIN_12(check_v1)"] >= 10 then [#"BIN_12(check_v2)"] else if [#"BIN_12(check_v1)"] < 10 then [#"BIN_12(check_v1)"] else null),
    #"Переименованные столбцы5" = Table.RenameColumns(#"Условный столбец добавлен5",{{"Пользовательский", "BIN_12(check_final)"}}),
    #"Условный столбец добавлен6" = Table.AddColumn(#"Переименованные столбцы5", "Validation Check", each if [BIN_12] = [#"BIN_12(check_final)"] then "BIN valid" else "BIN Invalid"),
    #"Измененный тип17" = Table.TransformColumnTypes(#"Условный столбец добавлен6",{{"DATE OF ISSUE", type date}, {"VALIDITY", type date}}),
    #"Добавлен пользовательский объект28" = Table.AddColumn(#"Измененный тип17", "Duration of Participation", each Number.Round(Duration.Days(Duration.From([VALIDITY]-[DATE OF ISSUE]))/365, 0)),
    #"Условный столбец добавлен7" = Table.AddColumn(#"Добавлен пользовательский объект28", "Forms of business organizations", each if Text.Contains([COMPANY], "Товарищество с ограниченной ответственностью") then "LLC/ТОО" else if Text.Contains([COMPANY], "ТОО") then "LLC/ТОО" else if Text.Contains([COMPANY], "Частная компания") then "LTD/ЧК" else if Text.Contains([COMPANY], "ЧК") then "LTD/ЧК" else if Text.Contains([COMPANY], "ТОВАРИЩЕСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ") then "LLC/ТОО" else if Text.Contains([COMPANY], "ЧАСТНАЯ КОМПАНИЯ") then "LTD/ЧК" else if Text.Contains([COMPANY], "TOO") then "LLC/ТОО" else if Text.Contains([COMPANY], "TОО") then "LLC/ТОО" else if Text.Contains([COMPANY], "Частная Компания") then "LTD/ЧК" else if Text.Contains([COMPANY], "ТОО") then "LLC/ТОО" else if Text.Contains([COMPANY], "Жауапкершілігі шектеулі серіктестік") then "LLC/ТОО" else if Text.Contains([COMPANY], "жауапкершілігі шектеулі серіктестік") then "LLC/ТОО" else if Text.Contains([COMPANY], "ЖШС") then "LLC/ТОО" else if Text.Contains([COMPANY], "жшс") then "LLC/ТОО" else if Text.Contains([COMPANY], "Жшс") then "LLC/ТОО" else if Text.Contains([COMPANY], "ЖАУАПКЕРШІЛІГІ ШЕКТЕУЛІ СЕРІКТЕСТІК") then "LLC/ТОО" else if Text.Contains([COMPANY], "жауапкершілігі шектеулі серіктестігі") then "LLC/ТОО" else if Text.Contains([COMPANY], "жеке компаниясы") then "LTD/ЧК" else if Text.Contains([COMPANY], "Жеке компаниясы") then "LTD/ЧК" else if Text.Contains([COMPANY], "ЖЕКЕ КОМПАНИЯСЫ") then "LTD/ЧК" else if Text.Contains([COMPANY], "Общественный фонд") then "Social Fund/ОФ" else if Text.Contains([COMPANY], "ОБЩЕСТВЕННЫЙ ФОНД") then "Social Fund/ОФ" else if Text.Contains([COMPANY], "общественный фонд") then "Social Fund/ОФ" else if Text.Contains([COMPANY], "Общественный Фонд") then "Social Fund/ОФ" else if Text.Contains([COMPANY], "Партнерство с ограниченной ответственностью") then "LLP/ПОО" else if Text.Contains([COMPANY], "ПОО") then "LLP/ПОО" else if Text.Contains([COMPANY], "ПАРТНЕРСТВО С ОГРАНИЧЕННОЙ ОТВЕТСТВЕННОСТЬЮ") then "LLP/ПОО" else if Text.Contains([COMPANY], "Партнерство с Ограниченной Ответственностью") then "LLP/ПОО" else if Text.Contains([COMPANY], "Некоммерческая организация") then "NPO/НКО" else if Text.Contains([COMPANY], "НЕКОММЕРЧЕСКАЯ ОРГАНИЗАЦИЯ") then "NPO/НКО" else if Text.Contains([COMPANY], "Некоммерческая организация") then "NPO/НКО" else if Text.Contains([COMPANY], "некоммерческая организация") then "NPO/НКО" else if Text.Contains([COMPANY], "Публичная компания") then "PLC/Публичная компания" else if Text.Contains([COMPANY], "публичная компания") then "PLC/Публичная компания" else if Text.Contains([COMPANY], "Публичная Компания") then "PLC/Публичная компания" else if Text.Contains([COMPANY], "ПУБЛИЧНАЯ КОМПАНИЯ") then "PLC/Публичная компания" else "Other/Другое"),
    #"Переименованные столбцы6" = Table.RenameColumns(#"Условный столбец добавлен7",{{"Forms of business organizations", "Forms of Business Organizations"}}),
    #"Измененный тип18" = Table.TransformColumnTypes(#"Переименованные столбцы6",{{"DATE OF REGISTRATION", type date}, {"Duration of Participation", Int64.Type}}),
    #"Переименованные столбцы7" = Table.RenameColumns(#"Измененный тип18",{{"CERTIFICATE №", "№"}}),
    #"Добавлен пользовательский объект29" = Table.AddColumn(#"Переименованные столбцы7", "AIFC_check", each Text.Middle([BIN FINAL],6,1)),
    #"Условный столбец добавлен8" = Table.AddColumn(#"Добавлен пользовательский объект29", "AIFC companies", each if [AIFC_check] = "9" then "AIFC" else "Not AIFC")
in
    #"Условный столбец добавлен8"
